#!/bin/sh

wd=$(pwd)

if [ ! -f "$wd/mac" ]; then
  curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
else
  echo "A $wd/mac setup script exists.\n"
  echo "To update the script from the thoughtbot/laptop repo, run"
  echo "rm mac && ./install"
fi

if [ ! -f "~/.laptop.local" ]; then
  cp "$wd/laptop.local" ~/.laptop.local
else
  echo "A ~/.laptop.local file already exists"
fi

if [ ! -d "$wd/logs" ]; then
  mkdir "$wd/logs"
fi
